name: RDP via Tailscale

on:
  workflow_dispatch: # run manually from Actions tab

jobs:
  rdp:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 1. Enable RDP
      - name: Enable Remote Desktop
        shell: pwsh
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 0
          Write-Host "✅ RDP enabled."

      # 2. Create RDP User
      - name: Create RDP User
        shell: pwsh
        run: |
          $username = "rdpuser"
          $password = "P@ssw0rd123!"
          $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser $username -Password $securePassword -FullName "RDP User" -Description "User for RDP"
          Add-LocalGroupMember -Group "Administrators" -Member $username
          Write-Host "✅ RDP user created: $username / $password"

      # 3. Install Tailscale
      - name: Install Tailscale
        shell: pwsh
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList @("/i", "`"$installerPath`"", "/qn", "/norestart") -Wait -NoNewWindow
          Write-Host "✅ Tailscale installed."

      # 4. Connect Tailscale
      - name: Connect to Tailscale
        shell: pwsh
        run: |
          $env:TS_AUTHKEY = "${{ secrets.TAILSCALE_AUTH_KEY }}"
          $tsPath = "C:\Program Files\Tailscale\tailscale.exe"

          # Use full path to tailscale.exe
          & "$tsPath" up --authkey $env:TS_AUTHKEY --accept-routes --accept-dns=false
          $ip = & "$tsPath" ip -4
          Write-Host "✅ Connected to Tailscale. Your IP: $ip"
     
     # 5. Keep alive
      - name: Keep Session Alive
        shell: pwsh
        run: |
          Write-Host "🚀 RDP is ready. Use your Tailscale IP to connect."
          Start-Sleep -Seconds 3600
          
